/** @type {import('stylelint').Config} */
export default {
 extends: ['stylelint-config-standard-scss'],
 plugins: ['stylelint-scss', 'stylelint-order'],
 rules: {
  'order/properties-order': [
   {
    properties: [
     'position',
     'inset',
     'top',
     'right',
     'bottom',
     'left',
     'z-index',
     'display',
     'flex',
     'flex-direction',
     'flex-wrap',
     'flex-flow',
     'justify-content',
     'align-items',
     'gap',
     'width',
     'min-width',
     'max-width',
     'height',
     'min-height',
     'max-height',
     'margin',
     'padding',
     'font',
     'font-size',
     'font-weight',
     'line-height',
     'text-align',
     'color',
     'background',
     'border',
     'border-radius',
     'box-shadow',
     'opacity',
    ],
   },
  ],
  // 'scss/dollar-variable-pattern': '^[_]?[a-z][a-zA-Z0-9]*$',
  'selector-class-pattern':
   '^[a-z]+(?:-[a-z0-9]+)*(?:__(?:[a-z0-9]+(?:-[a-z0-9]+)*))?(?:--[a-z0-9-]+)?$',
 },
 ignoreFiles: [
  '**/dist/**',
  '**/node_modules/**',
  '**/project_info/**',
  '**/public/**',
 ],
}
